Anton/todo list
FausT-VX/go_final_project pull request #1
Opened 2024-08-25 09:36 UTC by FausT-VX

2024-08-25 22:19 UTC, dirtymew requested changes
Привет Антон

хорошая работа:
 - документация
 - логирование
 - задания со звездочкой

есть что поправить и улучшить - дал комментарии

для первой итерации думаю достаточно

2024-08-25 22:19 UTC, dirtymew commented on .vscode/launch.json
> +{
это все лучше в .gitingone и не комитеть

2024-08-25 22:19 UTC, dirtymew commented on Makefile
> +	docker run -p 7540:7540 faustvx/todo_server:v1
раз есть .env - мб проще docker compose использовать ...

2024-08-25 22:19 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.23 AS build
лучше туже версию go использовать go 1.22.5 в go mod

2024-08-25 22:19 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o todo_server .
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 это лучше в ENV или .env( если использовать compose)

2024-08-25 22:19 UTC, dirtymew commented on Dockerfile
> +COPY web/ ./web/
хм кажется для сборки не нужна эта директория...

2024-08-25 22:19 UTC, dirtymew commented on Dockerfile
> +COPY go.mod go.sum ./
а зачем если потом все и так копируется - может COPY . .  достаточно

2024-08-25 22:19 UTC, dirtymew commented on Dockerfile
> +COPY --from=build /app/tests/settings.go /app/tests/settings.go
зачем? тесты в конейнере запускать планируются? думаю лишнее

2024-08-25 22:19 UTC, dirtymew commented on tests/db_2_test.go
> +	id, _ := res.LastInsertId()
зачем убрал - нужно вернуть

2024-08-25 22:19 UTC, dirtymew commented on tests/db_2_test.go
> +	envFile := "." + os.Getenv("TODO_DBFILE") // была ошибка в тесте os.Getenv("." + "TODO_DBFILE") переменной среды, начинающейся с точки нет :)
нет тут ошибки никакой - стоит вернуть тут все корректно было

2024-08-25 22:19 UTC, dirtymew commented on service/scheduler/scheduler.go
> +	begDate, err := time.Parse("20060102", date)
20060102 в константу и везде использовать

2024-08-25 22:19 UTC, dirtymew commented on models/models.go
> +// type Task struct { //сначала сделал через gorm, но не смог подогнать под тесты, потому что gorm добавляет в таблицу свои поля
ORM зло и вне курса - лучше учиться на чистых запросах

2024-08-25 22:19 UTC, dirtymew commented on models/models.go
> +	return "scheduler"
кажется лишнее и достаточно константы для этого

2024-08-25 22:19 UTC, dirtymew commented on models/models.go
> +type JsonTask struct {
можно - но кажется что Task было-бы достаточно...

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +	expectedPassword := os.Getenv("TODO_PASSWORD")
это не очень - не стоит в  ОС обращаться из хендлера - это дорого

стоит один раз при старте всю конфигурацию считать

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +		pass := os.Getenv("TODO_PASSWORD")
см коммент выше

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +	w.Write([]byte("{}"))
_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут и не зря

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +	log.Printf("Handler DeleteTask: id = %v\n", id)
лог на каждый запрос не стоит писать - лучше только на ошибки или использовать логгер с поддержкой разных уровне логирования и режим работы debug приложения

логирование тоже за рамками курса - править или нет на твое усмотрение

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +	idTask := strings.TrimSpace(task.ID)
хендлеры прям перегружены логикой валидацие - стоит это вынести в функции или отдельный пакет

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +	if strings.TrimSpace(task.Repeat) == "" {
тут мб стоит порефакторить вложеные if и else не очень выглядит...

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +	type TaskID struct {
ой а зачем? каждый раз структуру обьявлять?  - можно использовать уже имеющиеся
или на крайний случай отдельно обьявить один раз

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +		query = "SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date LIMIT 50"
лимит в параметрах у тебя...

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +		Limit  int    `db:"limit"`
limit   - этого нет в API  стоит убрать и задать константой

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +	type params struct {
стуктуры в хенждлерах не нужно создавать - если нужно то в пакете обьявляй вне функций

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-08-25 22:19 UTC, dirtymew commented on handlers/handlers.go
> +	rows, err := database.DB.NamedQuery(query, args)
о прям не хорошо - у тебя есть отдельный компонент database - он отвечает за взаимодействие с бд а не хенжлера - так зоны ответвенности размываются

закрой от экспорта database.DB и сделай ручки нужные - кажется что даже одного  метода database.Find(filter string) или database.Search(search string) достаточно

2024-08-25 22:19 UTC, dirtymew commented on database/database.go
> +// database/database.go
// database/database.go - лишний коммент

database/scheduler.db - я бы бд оставил в корне проекта поумолчанию - в пакетах не принято артефакты складывать

2024-08-25 22:19 UTC, dirtymew commented on database/database.go
> +		appPath, err := os.Executable()
мб лучше Getwd - os.Executable везде поразному работает

2024-08-25 22:19 UTC, dirtymew commented on database/database.go
> +var DB *sqlx.DB //Dbinstance
посмотри на задание про посылки - как там сделан storage 

и вообще архитектурно компоненты 

глобальная переменная с подключением - не очень хорошее решение

2024-08-25 22:19 UTC, dirtymew commented on database/database.go
> +	_, err := GetTaskByID(id)
тут ты делаешь 2 запроса - это не хорошо 

одного DELETE достаточно

если хочется ошибку - то используй RowsAffected

2024-08-25 22:19 UTC, dirtymew commented on database/database.go
> +// func ConnectDB(dbPath string) {
лишние комментарии стоит убрать

2024-08-25 22:19 UTC, dirtymew commented on main.go
> +	if err := database.ConnectDB(DbPath); err != nil {
не нашел где подключение к бд закрывается по завершению программы

2024-08-26 04:37 UTC, FausT-VX commented on database/database.go
> +		appPath, err := os.Executable()
Этот кусок кода из самого задания, которое кстати вообще содержит много косяков, включая кривые тесты. Мало того что тесты не сильно, но противоречат заданию. Так еще содержат как прямые косяки, например в виде некорректного получения переменной среды. 
![image](https://github.com/user-attachments/assets/36d7ba90-9ff0-43f7-9f49-ecbfc0bf2774)
 Кроме того тесты написаны только для локального тестирования, т.к. используют прямые запросы в локальную БД. Задачи в базу добавляют методом post http://localhost:7540/api/task, а проверяют записался ли он в базу просто запросом, место того чтобы использовать метод get по адресу http://localhost:7540/api/task?id=277
![image](https://github.com/user-attachments/assets/0911fc21-2686-4830-9884-618881b6ec2b)

2024-08-26 04:44 UTC, FausT-VX commented on .vscode/launch.json
> +{
.gitignore?
я понимаю что пароли нельзя коммитить, но задание то учебное :) И надо же как то ревьюеру его тестить.

2024-08-26 05:33 UTC, FausT-VX commented on database/database.go
> +var DB *sqlx.DB //Dbinstance
Ок, но я тоже это взял из примера, которой мы в докер контейнер закатывали в 11 спринте, как раз todo list. Думал что это best practices :)

2024-08-26 05:49 UTC, FausT-VX commented on Dockerfile
> +COPY go.mod go.sum ./
Когда сдавал задание по докеру, мне написали, что keit разделить файлы которые не меняются и редко меняются, с часто меняемыми, чтобы закешировались слои при сборке образа и пересборка будет идти быстрее.

2024-08-26 05:50 UTC, FausT-VX commented on Dockerfile
> +COPY --from=build /app/tests/settings.go /app/tests/settings.go
Они локально написаны, думал там запускать. Просто убрать забыл :)

2024-08-26 05:52 UTC, FausT-VX commented on Makefile
> +	docker run -p 7540:7540 faustvx/todo_server:v1
.env добавил чтобы потом для себя после сдачи задания прикрутить CI/CD

2024-08-26 05:53 UTC, FausT-VX commented on database/database.go
> +// database/database.go
ок, учту

2024-08-26 06:34 UTC, FausT-VX commented on database/database.go
> +// database/database.go
> // database/database.go - лишний коммент

Эти комменты VS code добавляет автоматом при сохранении, либо какое-то из расширений, не знаю где настраивается.

2024-08-26 06:43 UTC, FausT-VX commented on tests/db_2_test.go
> +	id, _ := res.LastInsertId()
> зачем убрал - нужно вернуть

не помню когда и зачем убрал но когда вернул:
![image](https://github.com/user-attachments/assets/c384b378-2d31-4466-882c-6af9505c304d)

2024-08-26 06:47 UTC, FausT-VX commented on tests/db_2_test.go
> +	envFile := "." + os.Getenv("TODO_DBFILE") // была ошибка в тесте os.Getenv("." + "TODO_DBFILE") переменной среды, начинающейся с точки нет :)
так тесты в паке tests? а файл бд теперь уже в корне, если вернут все тесты валятся, либо в переменные среды  и константу прописывать везде "../scheduler.db" и во всем остальном коде при использовании избавляться от лидирующей точки, проще тест поправить, который заведомо валиться.

2024-08-26 07:26 UTC, dirtymew commented on .vscode/launch.json
> +{
я про артефакт vscode - для задания это можно положить в .env и описать в документации

2024-08-26 07:26 UTC, dirtymew commented on tests/db_2_test.go
> +	envFile := "." + os.Getenv("TODO_DBFILE") // была ошибка в тесте os.Getenv("." + "TODO_DBFILE") переменной среды, начинающейся с точки нет :)
в настройках теста var DBFile = "../scheduler.db"

2024-08-26 07:26 UTC, dirtymew commented on Makefile
> +	docker run -p 7540:7540 faustvx/todo_server:v1
ну его удобно и для других целей использовать

2024-08-26 07:26 UTC, dirtymew commented on database/database.go
> +		appPath, err := os.Executable()
<img width="395" alt="image" src="https://github.com/user-attachments/assets/ce3420d0-6b95-4fcc-99b8-95503313ac87">

все корректно - тесты только свои можно добавить и поменять пути для win машин - остальное там корректно

то что тест лезет в бд это OK - так авторы решили делать проверки.
я бы так не делал без острой необходимости и сделал бы тесты "черного ящика" только по http API

2024-08-26 07:26 UTC, dirtymew commented on database/database.go
> +var DB *sqlx.DB //Dbinstance
если ты про задание с API то там чисто для ознакомление хранение сделано 

а вот в задании про посылки там как раз пример того как надо

2024-08-26 07:30 UTC, FausT-VX commented on database/database.go
> +	_, err := GetTaskByID(id)
Сделал, но:
![image](https://github.com/user-attachments/assets/74de3542-9e73-4d33-ae7f-20b49b05432f)

2024-08-26 19:13 UTC, dirtymew requested changes
Антон

критичные замечания не исправлены

2024-08-26 19:13 UTC, dirtymew commented on .gitignore
> +.vscode/launch.json
лучше всю папку .vscode

и в ветке файлы все еще есть

2024-08-26 19:13 UTC, dirtymew commented on handlers/handlers.go
> +
@FausT-VX тут не исправлено

2024-08-26 19:13 UTC, dirtymew commented on handlers/handlers.go
> +	w.Write(jsonResponse)
тут ошибка не обработана

2024-08-26 19:13 UTC, dirtymew commented on handlers/handlers.go
> +	type TaskID struct {
@FausT-VX не исправлено

2024-08-26 19:13 UTC, dirtymew commented on handlers/handlers.go
> +		query = "SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date LIMIT 50"
@FausT-VX не исправлено

2024-08-26 19:13 UTC, dirtymew commented on handlers/handlers.go
> +	type params struct {
@FausT-VX не исправлено

2024-08-26 19:13 UTC, dirtymew commented on handlers/handlers.go
> +func DBinit(db *sqlx.DB) {
а почему тут а не в database

2024-08-26 19:13 UTC, dirtymew commented on handlers/handlers.go
> +var DB *sqlx.DB //Dbinstance
тоже в database

2024-08-26 19:13 UTC, dirtymew commented on database/database.go
> +func GetTaskByID(db *sqlx.DB, id int) (models.JsonTask, error) {
а почему только 2 метода ? стоит и остальные реализовать тут

2024-08-26 19:13 UTC, dirtymew commented on handlers/handlers.go
> +	expectedPassword := os.Getenv("TODO_PASSWORD")
@FausT-VX неисправлено

2024-08-26 19:13 UTC, dirtymew commented on handlers/handlers.go
> +		pass := os.Getenv("TODO_PASSWORD")
@FausT-VX не исправлено

2024-08-26 19:13 UTC, dirtymew commented on main.go
> +	// fileServer := http.FileServer(http.Dir(WebDir))
убрать лишние комментарии

2024-08-26 19:13 UTC, dirtymew commented on tests/db_2_test.go
> +	envFile := "." + os.Getenv("TODO_DBFILE") // тогда хотя бы так, чтоб переменную среды не комментировать перед тестами
не верно - нужно вернуть -  я не понимаю проблемы - не нужно комментировать переменные среды

2024-08-27 09:00 UTC, closed without merging